bridges = []

[[instances]]
name = "snapmail"
id = "__snapmail"
dna_hash = "QmRMQDfvTNgYHLGVWZonSyg8iKqGMykZLK72btQ2r4xt4h"
uri = "file:dist/snapmail-dna.dna.json"

[[UIs]]
name = "SnapMail WebUI"
id = "snapmail_web_ui"
uri = "dir:../snapmail-ui/dist"

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "__snapmail"
