bridges = []

[[instances]]
name = "snapmail"
id = "__snapmail"
dna_hash = "QmVUGcceLHJm24BGRR6PFLe94XfgrQogddMBe1kwReg5Aq"
uri = "file:./dist/snapmail-dna.dna.json"

[[UIs]]
name = "SnapMail Web"
id = "snapmail_web_ui"
uri = "dir:./../snapmail-ui/dist"

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "__snapmail"
