bridges = []
persistence_dir = ''

[[agents]]
id = 'hc-run-agent'
keystore_file = 'Alice'
name = 'Alice'
public_address = 'HcSciaDXrXkqxwv7gukMChvazIuscvcrk457t8n88cmo95en4sPCEdDKvj4ucja'
test_agent = true

[[dnas]]
file = './dist/snapmail-dna.dna.json'
hash = 'Qmey1QZJ5hPyUqS337VpZGnSbzKK6FrZ6vSPnLP6UJHZZF'
id = '__snapmail'

[[instances]]
agent = 'hc-run-agent'
dna = '__snapmail'
id = '__snapmail'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = false
choose_free_port = false
id = 'snapmail_web_ui'

[[interfaces.instances]]
alias = 'test-instance'
id = '__snapmail'

[interfaces.driver]
port = 50000
type = 'websocket'

[[ui_bundles]]
id = 'snapmail_web_ui'
root_dir = './../snapmail-ui/dist'

[[ui_interfaces]]
bind_address = '127.0.0.1'
bundle = 'snapmail_web_ui'
dna_interface = 'snapmail_web_ui'
id = 'snapmail_web_ui'
port = 8888
reroute_to_root = false

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[network]
sim2h_url = 'ws://sim2h.harris-braun.com:9049'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
