bridges = []
persistence_dir = ''

[[agents]]
id = 'hc-run-agent'
keystore_file = 'Camille'
name = 'Camille'
public_address = 'HcScIfu459SHYhmt6z8M3XNqE73Kcqr9rPWOpIO5b4FvyzndOB8FxAAg6Faizmr'
test_agent = true

[[dnas]]
file = './dist/snapmail-dna.dna.json'
hash = 'QmSri5jCaxfwvVLQrNMir3aohbEWA9sH6deRtJAYboNuz8'
id = '__snapmail'

[[instances]]
agent = 'hc-run-agent'
dna = '__snapmail'
id = '__snapmail'

[instances.storage]
type = 'lmdb'
path = 'source_chain_camille'

[[interfaces]]
admin = false
choose_free_port = false
id = 'snapmail_web_ui'

[[interfaces.instances]]
alias = 'test-instance'
id = '__snapmail'

[interfaces.driver]
port = 50001
type = 'websocket'

[[ui_bundles]]
id = 'snapmail_web_ui'
root_dir = './../snapmail-ui/dist'

[[ui_interfaces]]
bind_address = '127.0.0.1'
bundle = 'snapmail_web_ui'
dna_interface = 'snapmail_web_ui'
id = 'snapmail_web_ui'
port = 8890
reroute_to_root = false

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[network]
sim2h_url = 'ws://sim2h.harris-braun.com:9050'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
